# Generated by Django 5.0.6 on 2024-07-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='Age',
            new_name='age',
        ),
    ]
